GET http://localhost:3000/energy
###
GET http://localhost:3000/review/1
###

get http://localhost:3000/eee

###
delete http://localhost:3000/img/1
###
POST http://localhost:3000/img
content-type: application/json

{
    "image": "sample"
}
###
POST http://localhost:3000/user
content-type: application/json

{
    "firstname": "Erik",
    "username": "Nishii",
    "pwd": "Fortnite"
}
###
PATCH http://localhost:3000/user
content-type: application/json

{
    "username": "Nishii",
    "pwd": "Fortnite"
}
###
GET http://localhost:3000/users
###

GET http://localhost:3000/salt/e

###
